### ISSUE TITLE
Set log group on the x-ray segment

### ISSUE THREAD

**Issue by garyd203** [garyd203/xraysink#17]
Be able to explicitly set the AWS CLoudwatch Group used for this segment. This appears to be set using the field `segment['aws']['cloudwatch_logs']['logGroup']` (according to the [Java SDK](https://github.com/aws/aws-xray-sdk-java/blob/af2fb0b29f175babecb46cedb964d8dc45a6e04c/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/AWSXRayRecorder.java#L466)). NB: More likely to be `log_group` since everything else is snakecased

None of the python plugins currently set this (as of SDK v2.6.0), and it is unknowable for execution environments like ECS anyway. So let's provide the convenience. aws/aws-xray-sdk-python#188 tracks the official SDK's implementation of this feature

**Comment by grandstairs** [comment]
You are a life-saver. Thank you so much for figuring out you have to add the `traceId` field to the log and specify the `Document: { aws: { cloudwatch_logs: { log_group: "name-goes-here"}}}` in order for cloudwatch to show logs related to the trace.


```
{
    "Id": "1-66d31855-6f5d130426895f3a46d02c27",
    "Duration": 0,
    "Segments": [
        {
            "Id": "6b2f00e244c2001a",
            "Document": {
                "id": "6b2f00e244c2001a",
                "name": "myservice",
                "start_time": 1725110357.4398508,
                "trace_id": "1-66d31855-6f5d130426895f3a46d02c27",
                "end_time": 1725110357.4400752,
                "aws": {
                    "cloudwatch_logs": {
                        "log_group": "appLogs"
                    }
                },
                "subsegments": [
                    {
                        "id": "ff18b78ebef2cf6d",
                        "name": "DatabaseCall",
                        "start_time": 1725110357.4398944,
                        "end_time": 1725110357.439969,
                        "http": {
                            "response": {
                                "status": 200
                            }
                        },
                    }
                ]
            }
        }
    ]
}
```

**Comment by garyd203** [comment]
Glad it helped @grandstairs
