### ISSUE TITLE
General use questions

### ISSUE THREAD

**Issue by brickfungus** [garyd203/xraysink#22]
I'm trying to get this going, but feeling like the documentation is confusing.

```# Basic asyncio X-Ray configuration
xray_recorder.configure(context=AsyncContext(), service="my-cute-little-service")

# Create a FastAPI app with various middleware
app = FastAPI()
app.add_middleware(MyTracingDependentMiddleware)  # Any middleware that is added earlier will have the X-Ray tracing context available to it
app.add_middleware(BaseHTTPMiddleware, dispatch=xray_middleware)
```

- which BastHTTPMiddleware is this referring to?
- what is xray_middlewhere
- do we import xraysink anywhere?
- I'm using decorators on my endpoints `@xray_recorder.capture_async("status")` should I continue using these?

**Comment by garyd203** [comment]
Hi, thanks for your feedback and your clear questions.

You're right, the documentation is a bit minimal at the moment. I'll attempt to address your questions, and use them to update the documentation as well. I'm guessing you are trying to use `xraysink` with a FastAPI app, so I will assume that for my answers.

Firstly, `xraysink` is intended to be used in addition to the core `aws_xray_sdk` library. So you will still need to install and configure that library.

> which BaseHTTPMiddleware is this referring to?

For the FastAPI example, we use the `BaseHTTPMiddleware` from Starlette (the base project for FastAPI). So you would import:

```
from starlette.middleware.base import BaseHTTPMiddleware
```

> what is xray_middleware

This is a FastAPI-compatible middleware function that will automatically add X-Ray instrumentation to every request received by your app. You would import it like this:

```
from xraysink.asgi.middleware import xray_middleware
```

> do we import xraysink anywhere?

For FastAPI, you would import the `xray_middleware` middleware function and add it to your app, as above.

> I'm using decorators on my endpoints @xray_recorder.capture_async("status") should I continue using these?

No, `xray_middleware` is intended to replace this technique. The idea of middleware is that you can apply some standard code to every request that your application receives - in this case, `xray_middleware` adds the X-Ray instrumentation.

Hope this helps :)

**Comment by brickfungus** [comment]
thank you @garyd203 this was exactly what I needed to get it working 👍

**Comment by SLinAppliedBiomath** [comment]
Hi, found this after digging around with xray + FastApi for a bit. 
Is AsyncContext necessary, from the documentation/reading the code it seems to be used if you are spinning off Tasks. But for an async handler (like "async def") which are coroutines, do we still need to use AsyncContext?
