### ISSUE TITLE
tracing exclusion rules for FastAPI endpoints

### ISSUE THREAD

**Issue by smcoll** [garyd203/xraysink#38]
Very cool - thanks for the FastAPI middleware.  Since the middleware means we don't have to decorate each function, i have the opposite problem - a situation where i'd like to exclude tracing for a particular endpoint.  Is there a pattern for that which the AWS X-Ray SDK uses in cases like that?  A function decorator?  A path config used by the middleware?

**Comment by garyd203** [comment]
HI @smcoll , thanks for your question. The X-Ray approach is to instrument everything, and then use sampling rules to control the trace output.

For example, I don't want tracing for my health checks, so in the console I have added a sampling rule that matches the URL path `/health` and is set to a rate of `Limit to 0 r/sec, then 0% fixed rate`.

Does that address your use case?

**Comment by smcoll** [comment]
Yes- thank you.
